databases:
  db:
    storage: postgresql
    transaction_strategy: dbresolve_readcommitted
    dsn: postgresql://postgres:secret@gcms_dev_pg:5432/guillotina
    read_only: false
    pool_size: 100
asgi_server: uvicorn
store_json: true
applications:
  - guillotina.contrib.workflows
  - guillotina.contrib.vocabularies
  - guillotina.contrib.dbusers
  - guillotina.contrib.mailer
  - guillotina.contrib.email_validation
  - guillotina.contrib.cache
  - guillotina.contrib.catalog.pg
  - guillotina_volto
mailer:
  utility: guillotina.contrib.mailer.utility.PrintingMailerUtility
host: 0.0.0.0
address: 8081
static:
  - favicon.png: static/favicon.png
  - assets: guillotina:static/assets
  - swagger_static: guillotina.contrib.swagger:static
container_types:
  - Site
root_user:
  password: root
auth_extractors:
  - guillotina.auth.extractors.BearerAuthPolicy
  - guillotina.auth.extractors.BasicAuthPolicy
  - guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
  - guillotina.auth.validators.SaltedHashPasswordValidator
  - guillotina.auth.validators.JWTValidator
redis:
  host: localhost
  port: 6379
jwt:
  secret: secret
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
  +manage: guillotina:static/gmi
cors:
  allow_origin:
    - '*'
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - OPTIONS
    - PUT
  allow_headers:
    - '*'
  expose_headers:
    - '*'
  allow_credentials: true
  max_age: 3660
allow_register: true
global_disallowed_types:
  - User
  - UserManager
  - Group
  - GroupManager
  - Item
  - Container
  - Folder
default_blocks:
  Document:
    blocks:
      tile1:
        '@type': title
      tile2:
        '@type': description
      tile3:
        text: null
        '@type': text
    blocks_layout:
      items:
      - tile1
      - tile2
      - tile3
  Container:
    blocks:
      tile1:
        '@type': title
      tile2:
        '@type': description
      tile3:
        text: null
        '@type': text
    blocks_layout:
      items:
        - tile1
        - tile2
        - tile3
allow_discussion_types:
  - Document
