import fs from 'fs';
import path from 'path';
import cryptoRandomString from 'crypto-random-string';
import { pathToFileURL } from 'node:url';

const titleCase = (w: string) =>
  w.slice(0, 1).toUpperCase() + w.slice(1, w.length);

function nameFromPath(filePath: string) {
  const normalizedPath =
    filePath.replace(/[@~./\\:\s-]/gi, '') ||
    cryptoRandomString({ length: 10, characters: 'abcdefghijk' });

  return normalizedPath
    .split('-')
    .map((w, i) => (i > 0 ? titleCase(w) : w))
    .join('');
}

function getViteLoaderCode(extenders: string[]) {
  let buf = `/*
Don't change this file manually.
It is autogenerated by @plone/registry.
Instead, change the "addons" registration in the app.
*/\n`;

  const extendersToLoad: string[] = [];

  extenders.forEach((extenderPath) => {
    const defaultImport = nameFromPath(extenderPath);
    const fileUrl = pathToFileURL(extenderPath).href;
    buf += `import ${defaultImport} from '${fileUrl}';\n`;
    extendersToLoad.push(defaultImport);
  });

  buf += `
const safeWrapper = (func) => (config, context) => {
  const res = func(config, context);
  if (typeof res === 'undefined') {
    throw new Error("Vite extension function doesn't return config");
  }
  return res;
};

const load = (config, context = {}) => {
  const addonLoaders = [${extendersToLoad.join(', ')}];
  if (!addonLoaders.every((el) => typeof el === 'function')) {
    throw new TypeError(
      'Each addon has to provide a function applying its Vite extension to the app configuration.',
    );
  }
  return addonLoaders.reduce(
    (acc, apply) => safeWrapper(apply)(acc, context),
    config,
  );
};
export default load;
`;

  return buf;
}

export function createViteLoader(extenders: string[]) {
  const viteLoaderPath = path.join(process.cwd(), '.plone', 'vite.loader.js');
  const code = getViteLoaderCode(extenders);
  fs.writeFileSync(viteLoaderPath, code);
  return viteLoaderPath;
}

export { getViteLoaderCode, nameFromPath };
