import fs from 'fs';
import path from 'path';

function buildLoaderCode(addonsStylesInfo: Array<string> = []) {
  let buf = `/*
Don't change this file manually.
It is autogenerated by @plone/registry.
Add a ./styles/main.css in your add-on to load your add-on styles in the app.
*/

`;
  addonsStylesInfo.forEach((addon) => {
    const customization = `${addon}/styles/main.css`;
    const line = `@import '${customization}';\n`;
    buf += line;
  });

  return buf;
}

export function createAddonsStyleLoader(addonsStylesInfo: Array<string>) {
  const addonsLoaderPath = path.join(process.cwd(), '.addons.styles.css');

  fs.writeFileSync(addonsLoaderPath, buildLoaderCode(addonsStylesInfo));
}

export { buildLoaderCode };
