import config from '@plone/registry';
import { ContentTypeCondition } from '@plone/slots/src/helpers';
// @ts-expect-error - load-volto-addons is generated by webpack on the fly, see next.config.mjs
import applyAddonConfiguration, { addonsInfo } from 'load-volto-addons';
import Event from '@/views/Event/Event';
import Page from '@/views/Page/Page';

applyAddonConfiguration(config);

config.settings = {
  ...config.settings,
  apiPath: process.env.NEXT_PUBLIC_VERCEL_URL
    ? // Vercel does not prepend the schema to the NEXT_PUBLIC_VERCEL_URL automatic env var
      `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`
    : 'http://localhost:3000',
  addonsInfo,
};

config.slots = {
  ...(config.slots || {}),
};

config.registerSlotComponent({
  slot: 'main',
  name: 'view',
  component: Page,
  predicates: [ContentTypeCondition(['Document', 'Plone Site'])],
});

config.registerSlotComponent({
  slot: 'main',
  name: 'view',
  component: Event,
  predicates: [ContentTypeCondition(['Event'])],
});

export { config };
