import config from '@plone/registry';
// @ts-expect-error - load-volto-addons is generated by webpack on the fly, see next.config.mjs
import applyAddonConfiguration, { addonsInfo } from 'load-volto-addons';
import Page from '@/views/Page/Page';

applyAddonConfiguration(config);

config.settings = {
  ...config.settings,
  apiPath: process.env.NEXT_PUBLIC_VERCEL_URL
    ? // Vercel does not prepend the schema to the NEXT_PUBLIC_VERCEL_URL automatic env var
      `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`
    : 'http://localhost:3000',
  addonsInfo,
};

config.views = {
  ...config.views,
  contentTypesViews: {
    'Plone Site': Page,
    Document: Page,
  },
  defaultView: Page,
};

export { config };
