version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    # Cancel the Read the Docs build
    # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
    - exit 183;
