# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "20"
  jobs:
    post_install:
      # Install dependencies defined in your ``package.json``
      # - npm ci
      # Install any other extra dependencies to build the docs
      - npm install -g pnpm@latest
      - pnpm build:registry
      - (cd packages/volto && pnpm build-storybook -o ../../_build/html/storybook)
      - make rtd-pr-preview
#  commands:
#    - make rtd-pr-preview

# Build documentation in the "docs/" directory with Sphinx
#sphinx:
#  configuration: docs/conf.py

# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
#python:
#  install:
#    - requirements: docs/requirements.txt
