packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'apps/seven'
  - 'apps/quanta'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # exclude Volto packages, leaving them as reference
  - '!packages/volto*'
  - '!packages/coresandbox'

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  react-aria-components: ^1.7.0
  react-i18next: ^15.4.1
  react-router: 7.4.0
  '@react-router/dev': 7.4.0
  '@react-router/node': 7.4.0
  '@react-router/serve': 7.4.0
  '@tanstack/react-query': ^5.59.0
  release-it: ^18.1.2
  typescript: ^5.7.3
  vitest: ^2.1.9
  '@vitest/coverage-v8': ^2.1.9
  vite: ^5.4.9
