packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'apps/seven'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # exclude Volto packages, leaving them as reference
  - '!packages/volto*'
  - '!packages/coresandbox'

# The default pnpm catalog is loaded from `catalog.json` using `.pnpmfile.cjs`.
# If you want to customize the versions of the catalog, do it in there.
