packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'apps/*'
  - 'apps/plone/src/addons/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!packages/volto-guillotina'
