export const controlPanelsIcons: {
    default: any;
    'dexterity-types': any;
    'date-and-time': any;
    language: any;
    mail: any;
    navigation: any;
    site: any;
    search: any;
    socialmedia: any;
    editing: any;
    imaging: any;
    markup: any;
    'moderate-comments': any;
    security: any;
    users: any;
    groups: any;
    addons: any;
    rules: any;
    undo: any;
    aliases: any;
    relations: any;
};
export function filterControlPanels(controlpanels: any): any;
export function filterControlPanelsSchema(controlpanel: any): any;
