/**
 * Action types.
 * @module constants/ActionTypes
 */

export const ADD_CONTENT = 'ADD_CONTENT';
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const ADD_CONTENT_FAIL = 'ADD_CONTENT_FAIL';

export const DELETE_CONTENT = 'DELETE_CONTENT';
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
export const DELETE_CONTENT_FAIL = 'DELETE_CONTENT_FAIL';

export const EDIT_CONTENT = 'EDIT_CONTENT';
export const EDIT_CONTENT_SUCCESS = 'EDIT_CONTENT_SUCCESS';
export const EDIT_CONTENT_FAIL = 'EDIT_CONTENT_FAIL';

export const GET_BREADCRUMBS = 'GET_BREADCRUMBS';
export const GET_BREADCRUMBS_SUCCESS = 'GET_BREADCRUMBS_SUCCESS';
export const GET_BREADCRUMBS_FAIL = 'GET_BREADCRUMBS_FAIL';

export const GET_CONTENT = 'GET_CONTENT';
export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS';
export const GET_CONTENT_FAIL = 'GET_CONTENT_FAIL';

export const GET_NAVIGATION = 'GET_NAVIGATION';
export const GET_NAVIGATION_SUCCESS = 'GET_NAVIGATION_SUCCESS';
export const GET_NAVIGATION_FAIL = 'GET_NAVIGATION_FAIL';

export const GET_SCHEMA = 'GET_SCHEMA';
export const GET_SCHEMA_SUCCESS = 'GET_SCHEMA_SUCCESS';
export const GET_SCHEMA_FAIL = 'GET_SCHEMA_FAIL';

export const GET_WORKFLOW = 'GET_WORKFLOW';
export const GET_WORKFLOW_SUCCESS = 'GET_WORKFLOW_SUCCESS';
export const GET_WORKFLOW_FAIL = 'GET_WORKFLOW_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const TRANSITION_WORKFLOW = 'TRANSITION_WORKFLOW';
export const TRANSITION_WORKFLOW_SUCCESS = 'TRANSITION_WORKFLOW_SUCCESS';
export const TRANSITION_WORKFLOW_FAIL = 'TRANSITION_WORKFLOW_FAIL';
