/**
 * Action types.
 * @module constants/ActionTypes
 */

export const ADD_CONTENT_PENDING = 'ADD_CONTENT_PENDING';
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const ADD_CONTENT_FAIL = 'ADD_CONTENT_FAIL';

export const COPY = 'COPY';

export const COPY_PENDING = 'COPY_PENDING';
export const COPY_SUCCESS = 'COPY_SUCCESS';
export const COPY_FAIL = 'COPY_FAIL';

export const CUT = 'CUT';

export const DELETE_CONTENT_PENDING = 'DELETE_CONTENT_PENDING';
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
export const DELETE_CONTENT_FAIL = 'DELETE_CONTENT_FAIL';

export const EDIT_CONTENT_PENDING = 'EDIT_CONTENT_PENDING';
export const EDIT_CONTENT_SUCCESS = 'EDIT_CONTENT_SUCCESS';
export const EDIT_CONTENT_FAIL = 'EDIT_CONTENT_FAIL';

export const GET_BREADCRUMBS_PENDING = 'GET_BREADCRUMBS_PENDING';
export const GET_BREADCRUMBS_SUCCESS = 'GET_BREADCRUMBS_SUCCESS';
export const GET_BREADCRUMBS_FAIL = 'GET_BREADCRUMBS_FAIL';

export const GET_CONTENT_PENDING = 'GET_CONTENT_PENDING';
export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS';
export const GET_CONTENT_FAIL = 'GET_CONTENT_FAIL';

export const GET_NAVIGATION_PENDING = 'GET_NAVIGATION_PENDING';
export const GET_NAVIGATION_SUCCESS = 'GET_NAVIGATION_SUCCESS';
export const GET_NAVIGATION_FAIL = 'GET_NAVIGATION_FAIL';

export const GET_SCHEMA_PENDING = 'GET_SCHEMA_PENDING';
export const GET_SCHEMA_SUCCESS = 'GET_SCHEMA_SUCCESS';
export const GET_SCHEMA_FAIL = 'GET_SCHEMA_FAIL';

export const GET_TYPES_PENDING = 'GET_TYPES_PENDING';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAIL = 'GET_TYPES_FAIL';

export const GET_WORKFLOW_PENDING = 'GET_WORKFLOW_PENDING';
export const GET_WORKFLOW_SUCCESS = 'GET_WORKFLOW_SUCCESS';
export const GET_WORKFLOW_FAIL = 'GET_WORKFLOW_FAIL';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const MOVE_PENDING = 'MOVE_PENDING';
export const MOVE_SUCCESS = 'MOVE_SUCCESS';
export const MOVE_FAIL = 'MOVE_FAIL';

export const SEARCH_CONTENT_PENDING = 'SEARCH_CONTENT_PENDING';
export const SEARCH_CONTENT_SUCCESS = 'SEARCH_CONTENT_SUCCESS';
export const SEARCH_CONTENT_FAIL = 'SEARCH_CONTENT_FAIL';

export const TRANSITION_WORKFLOW_PENDING = 'TRANSITION_WORKFLOW_PENDING';
export const TRANSITION_WORKFLOW_SUCCESS = 'TRANSITION_WORKFLOW_SUCCESS';
export const TRANSITION_WORKFLOW_FAIL = 'TRANSITION_WORKFLOW_FAIL';
