// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/ok": {
    params: {};
  };
  "/reset-fetcher": {
    params: {};
  };
  "/login/*": {
    params: {
      "*": string;
    };
  };
  "/logout/*": {
    params: {
      "*": string;
    };
  };
  "/@@add/*": {
    params: {
      "*": string;
    };
  };
  "/@@edit/*": {
    params: {
      "*": string;
    };
  };
  "/controlpanel": {
    params: {};
  };
  "/controlpanel/:id": {
    params: {
      "id": string;
    };
  };
  "/test-layout/*": {
    params: {
      "*": string;
    };
  };
  "/@search/*": {
    params: {
      "*": string;
    };
  };
  "/@breadcrumbs/*": {
    params: {
      "*": string;
    };
  };
  "/@objectBrowserWidget/*": {
    params: {
      "*": string;
    };
  };
  "/@createContent/*": {
    params: {
      "*": string;
    };
  };
  "/layers.css": {
    params: {};
  };
  "/sitemap": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/@@contents/@@delete/*": {
    params: {
      "*": string;
    };
  };
  "/@@contents/@@upload/*": {
    params: {
      "*": string;
    };
  };
  "/@@contents/@@order/*": {
    params: {
      "*": string;
    };
  };
  "/@@contents/@@paste/*": {
    params: {
      "*": string;
    };
  };
  "/@@contents/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/ok" | "/reset-fetcher" | "/login/*" | "/logout/*" | "/@@add/*" | "/@@edit/*" | "/controlpanel" | "/controlpanel/:id" | "/test-layout/*" | "/@search/*" | "/@breadcrumbs/*" | "/@objectBrowserWidget/*" | "/@createContent/*" | "/layers.css" | "/sitemap" | "/search" | "/*" | "/@@contents/@@delete/*" | "/@@contents/@@upload/*" | "/@@contents/@@order/*" | "/@@contents/@@paste/*" | "/@@contents/*";
  };
  "okroute.tsx": {
    id: "ok";
    page: "/ok";
  };
  "reset-fetcher.tsx": {
    id: "reset-fetcher";
    page: "/reset-fetcher";
  };
  "../../../packages/cmsui/routes/layout.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/layout";
    page: "/login/*" | "/logout/*" | "/@@add/*" | "/@@edit/*" | "/controlpanel" | "/controlpanel/:id" | "/test-layout/*";
  };
  "../../../packages/cmsui/routes/auth/login.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/auth/login";
    page: "/login/*";
  };
  "../../../packages/cmsui/routes/auth/logout.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/auth/logout";
    page: "/logout/*";
  };
  "../../../packages/cmsui/routes/add.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/add";
    page: "/@@add/*";
  };
  "../../../packages/cmsui/routes/edit.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/edit";
    page: "/@@edit/*";
  };
  "../../../packages/cmsui/routes/controlpanels.tsx": {
    id: "index-controlpanel";
    page: "/controlpanel";
  };
  "../../../packages/cmsui/routes/controlpanel.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/controlpanel";
    page: "/controlpanel/:id";
  };
  "../../../packages/cmsui/routes/test.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/test";
    page: "/test-layout/*";
  };
  "../../../packages/cmsui/routes/search.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/search";
    page: "/@search/*";
  };
  "../../../packages/cmsui/routes/breadcrumbs.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/breadcrumbs";
    page: "/@breadcrumbs/*";
  };
  "../../../packages/cmsui/routes/objectBrowserWidget.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/objectBrowserWidget";
    page: "/@objectBrowserWidget/*";
  };
  "../../../packages/cmsui/routes/api/createContent.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/api/createContent";
    page: "/@createContent/*";
  };
  "../../../packages/publicui/routes/index.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/index";
    page: "/" | "/layers.css" | "/sitemap" | "/search" | "/*";
  };
  "../../../packages/publicui/routes/content.tsx": {
    id: "content-index";
    page: "/";
  } | {
    id: "content";
    page: "/*";
  };
  "../../../packages/publicui/routes/layers.css.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/layers.css";
    page: "/layers.css";
  };
  "../../../packages/publicui/routes/sitemap.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/sitemap";
    page: "/sitemap";
  };
  "../../../packages/publicui/routes/search.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/search";
    page: "/search";
  };
  "../../../packages/contents/routes/layout.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/layout";
    page: "/@@contents/@@delete/*" | "/@@contents/@@upload/*" | "/@@contents/@@order/*" | "/@@contents/@@paste/*" | "/@@contents/*";
  };
  "../../../packages/contents/routes/delete.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/delete";
    page: "/@@contents/@@delete/*";
  };
  "../../../packages/contents/routes/upload.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/upload";
    page: "/@@contents/@@upload/*";
  };
  "../../../packages/contents/routes/order.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/order";
    page: "/@@contents/@@order/*";
  };
  "../../../packages/contents/routes/paste.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/paste";
    page: "/@@contents/@@paste/*";
  };
  "../../../packages/contents/routes/contents.tsx": {
    id: "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/contents";
    page: "/@@contents/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "ok": typeof import("./app/okroute.tsx");
  "reset-fetcher": typeof import("./app/reset-fetcher.tsx");
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/layout": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/auth/login": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/auth/logout": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/add": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/edit": unknown;
  "index-controlpanel": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/controlpanel": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/test": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/search": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/breadcrumbs": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/objectBrowserWidget": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/cmsui/routes/api/createContent": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/index": unknown;
  "content-index": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/layers.css": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/sitemap": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/publicui/routes/search": unknown;
  "content": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/layout": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/delete": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/upload": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/order": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/paste": unknown;
  "/home/timo/Documents/Kitconcept/workspace/volto/packages/contents/routes/contents": unknown;
};