/*
Don't change this file manually.
It is autogenerated by @plone/registry.
Instead, change the "addons" registration in the app.
*/

const safeWrapper = (func) => (config, context) => {
  const res = func(config, context);
  if (typeof res === 'undefined') {
    throw new Error("Vite extension function doesn't return config");
  }
  return res;
};

const load = (config, context = {}) => {
  const addonLoaders = [];
  if (!addonLoaders.every((el) => typeof el === 'function')) {
    throw new TypeError(
      'Each addon has to provide a function applying its Vite extension to the app configuration.',
    );
  }
  return addonLoaders.reduce(
    (acc, apply) => safeWrapper(apply)(acc, context),
    config,
  );
};
export default load;
