import Contents from './Contents';
import type { Meta, StoryObj } from '@storybook/react';

import '../../styles/basic/main.css';
import '../../styles/quanta/main.css';

const meta = {
  title: 'Views/Contents',
  component: Contents,
  tags: ['autodocs'],
} satisfies Meta<typeof Contents>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: 'Section name',
    pathname: '/folder',
    objectActions: [
      {
        id: 'folderContents',
        title: 'Contents',
        icon: 'contents',
        url: '/folder/contents',
      },
    ],
    loading: false,
    orderContent: async (baseUrl, id, delta) => {
      console.log(`now PATCH https://api${baseUrl} with payload:
{
  "ordering": {
    "obj_id": "${id}",
    "delta": ${delta},
  },
}`);
    },
    addableTypes: [
      {
        '@id': 'https://demo.plone.org/@types/Document',
        id: 'Document',
        title: 'Page',
      },
      {
        '@id': 'https://demo.plone.org/@types/Event',
        id: 'Event',
        title: 'Event',
      },
      {
        '@id': 'https://demo.plone.org/@types/Image',
        id: 'Image',
        title: 'Image',
      },
      {
        '@id': 'https://demo.plone.org/@types/Link',
        id: 'Link',
        title: 'Link',
      },
      {
        '@id': 'https://demo.plone.org/@types/News Item',
        id: 'News Item',
        title: 'News Item',
      },
    ],
    items: [
      {
        '@id': 'https://demo.plone.org/images',
        '@type': 'Document',
        CreationDate: '2024-02-14T22:06:52+00:00',
        Creator: 'plone-6-demo-site',
        Date: '2024-02-14T22:06:52+00:00',
        Description: 'Image bank.',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2024-02-14T22:06:52+00:00',
        Subject: [],
        Title: 'Images',
        Type: 'Page',
        UID: '7b00238f184342a7a85ef4463380ac37',
        author_name: null,
        cmf_uid: null,
        commentators: [],
        created: '2024-02-14T22:06:52+00:00',
        description: 'Image bank.',
        effective: '1969-12-31T00:00:00+00:00',
        end: null,
        exclude_from_nav: true,
        expires: '2499-12-31T00:00:00+00:00',
        getIcon: null,
        getId: 'images',
        getObjSize: '0 KB',
        getPath: '/Plone/images',
        getRemoteUrl: null,
        getURL: 'https://demo.plone.org/images',
        hasPreviewImage: null,
        head_title: null,
        id: 'images',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        listCreators: ['plone-6-demo-site'],
        location: null,
        mime_type: 'text/plain',
        modified: '2024-02-14T22:06:52+00:00',
        nav_title: null,
        portal_type: 'Document',
        review_state: 'published',
        start: null,
        sync_uid: null,
        title: 'Images',
        total_comments: 0,
        type_title: 'Page',
      },
      {
        '@id': 'https://demo.plone.org/my-page',
        '@type': 'Document',
        CreationDate: '2024-02-15T11:22:02+00:00',
        Creator: 'admin',
        Date: '2024-02-15T11:22:02+00:00',
        Description: 'This is my page',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2024-02-15T11:22:02+00:00',
        Subject: ['its-mine'],
        Title: 'My page',
        Type: 'Page',
        UID: '51cb4490e3a346349093f6c423c8f28a',
        author_name: null,
        cmf_uid: null,
        commentators: [],
        created: '2024-02-15T11:22:02+00:00',
        description: 'This is my page',
        effective: '1969-12-31T00:00:00+00:00',
        end: null,
        exclude_from_nav: false,
        expires: '2499-12-31T00:00:00+00:00',
        getIcon: null,
        getId: 'my-page',
        getObjSize: '0 KB',
        getPath: '/Plone/my-page',
        getRemoteUrl: null,
        getURL: 'https://demo.plone.org/my-page',
        hasPreviewImage: null,
        head_title: null,
        id: 'my-page',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        listCreators: ['admin'],
        location: null,
        mime_type: 'text/plain',
        modified: '2024-02-15T11:22:02+00:00',
        nav_title: null,
        portal_type: 'Document',
        review_state: 'private',
        start: null,
        sync_uid: null,
        title: 'My page',
        total_comments: 0,
        type_title: 'Page',
      },
    ],
  },
};
