[
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/Products.CMFPlacefulWorkflow',
    description:
      'Aggiunge a Plone la possibilità di modificare il workflow per tipo di contenuto in ogni sezione. Questa funzionalità dipende dai contenuti standard di Plone',
    id: 'Products.CMFPlacefulWorkflow',
    install_profile_id: 'Products.CMFPlacefulWorkflow:CMFPlacefulWorkflow',
    is_installed: false,
    profile_type: 'default',
    title: 'Supporto per le politiche di workflow (CMFPlacefulWorkflow)',
    uninstall_profile_id: 'Products.CMFPlacefulWorkflow:uninstall',
    upgrade_info: {},
    version: '3.0.3',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/collective.feedback',
    description: 'Installs the collective.feedback add-on.',
    id: 'collective.feedback',
    install_profile_id: 'collective.feedback:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.feedback',
    uninstall_profile_id: 'collective.feedback:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1201',
      newVersion: '1201',
      required: false,
    },
    version: '1.1.3',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.geolocationbehavior',
    description: 'Installs the collective.geolocationbehavior package',
    id: 'collective.geolocationbehavior',
    install_profile_id: 'collective.geolocationbehavior:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.geolocationbehavior',
    uninstall_profile_id: 'collective.geolocationbehavior:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '5',
      newVersion: '5',
      required: false,
    },
    version: '1.7.1',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/collective.taxonomy',
    description: 'Registers control panel and default settings.',
    id: 'collective.taxonomy',
    install_profile_id: 'collective.taxonomy:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.taxonomy',
    uninstall_profile_id: 'collective.taxonomy:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '2000',
      newVersion: '2000',
      required: false,
    },
    version: '3.0.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.tiles.collection',
    description: 'Installa il plugin collective.tiles.collection.',
    id: 'collective.tiles.collection',
    install_profile_id: 'collective.tiles.collection:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Collective tiles: collection',
    uninstall_profile_id: 'collective.tiles.collection:uninstall',
    upgrade_info: {},
    version: '2.0.0',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/collective.venue',
    description: 'Dexterity venue type extension with geolocation support.',
    id: 'collective.venue',
    install_profile_id: 'collective.venue:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.venue con supporto alla geolocalizzazione',
    uninstall_profile_id: 'collective.venue:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '2',
      newVersion: '2',
      required: false,
    },
    version: '4.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.cookieconsent',
    description: 'Installs the collective.volto.cookieconsent add-on.',
    id: 'collective.volto.cookieconsent',
    install_profile_id: 'collective.volto.cookieconsent:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Volto Cookieconsent',
    uninstall_profile_id: 'collective.volto.cookieconsent:uninstall',
    upgrade_info: {},
    version: '1.1.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.dropdownmenu',
    description: 'Install collective.volto.dropdownmenu.',
    id: 'collective.volto.dropdownmenu',
    install_profile_id: 'collective.volto.dropdownmenu:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto Dropdown Menu',
    uninstall_profile_id: 'collective.volto.dropdownmenu:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1100',
      newVersion: '1100',
      required: false,
    },
    version: '1.3.0',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.enhancedlinks',
    description: 'Installs the collective.volto.enhancedlinks add-on.',
    id: 'collective.volto.enhancedlinks',
    install_profile_id: 'collective.volto.enhancedlinks:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto: Enhanced Links',
    uninstall_profile_id: 'collective.volto.enhancedlinks:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1001',
      newVersion: '1001',
      required: false,
    },
    version: '1.1.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.formsupport',
    description: 'Install collective.volto.formsupport',
    id: 'collective.volto.formsupport',
    install_profile_id: 'collective.volto.formsupport:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto: Form support',
    uninstall_profile_id: 'collective.volto.formsupport:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1300',
      newVersion: '1300',
      required: false,
    },
    version: '3.0.2',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.gdprcookie',
    description: 'Installa collective.volto.gdprcookie',
    id: 'collective.volto.gdprcookie',
    install_profile_id: 'collective.volto.gdprcookie:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto: GDPR Cookies management',
    uninstall_profile_id: 'collective.volto.gdprcookie:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.0.3',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.secondarymenu',
    description: 'Install collective.volto.secondarymenu.',
    id: 'collective.volto.secondarymenu',
    install_profile_id: 'collective.volto.secondarymenu:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto Secondary Menu',
    uninstall_profile_id: 'collective.volto.secondarymenu:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.1.0',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.sitesettings',
    description: 'Installa collective.volto.sitesettings',
    id: 'collective.volto.sitesettings',
    install_profile_id: 'collective.volto.sitesettings:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.volto.sitesettings',
    uninstall_profile_id: 'collective.volto.sitesettings:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.0.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.slimheader',
    description: 'Installs the collective.volto.slimheader add-on.',
    id: 'collective.volto.slimheader',
    install_profile_id: 'collective.volto.slimheader:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.volto.slimheader',
    uninstall_profile_id: 'collective.volto.slimheader:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.0.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.socialsettings',
    description: 'Installs the collective.volto.socialsettings add-on.',
    id: 'collective.volto.socialsettings',
    install_profile_id: 'collective.volto.socialsettings:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.volto.socialsettings',
    uninstall_profile_id: 'collective.volto.socialsettings:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1001',
      newVersion: '1001',
      required: false,
    },
    version: '0.2.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.subfooter',
    description: 'Install collective.volto.subfooter.',
    id: 'collective.volto.subfooter',
    install_profile_id: 'collective.volto.subfooter:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto Subfooter',
    uninstall_profile_id: 'collective.volto.subfooter:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.1.0',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.volto.subsites',
    description: 'Installa collective.volto.subsites.',
    id: 'collective.volto.subsites',
    install_profile_id: 'collective.volto.subsites:default',
    is_installed: true,
    profile_type: 'default',
    title: 'collective.volto.subsites',
    uninstall_profile_id: 'collective.volto.subsites:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1200',
      newVersion: '1200',
      required: false,
    },
    version: '1.5.0',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/collective.z3cform.datagridfield',
    description: 'Install collective.z3cform.datagridfield',
    id: 'collective.z3cform.datagridfield',
    install_profile_id: 'collective.z3cform.datagridfield:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Data Grid Field for z3c.form',
    uninstall_profile_id: 'collective.z3cform.datagridfield:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '5',
      newVersion: '5',
      required: false,
    },
    version: '3.0.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/design.plone.contenttypes',
    description: 'Installs the design.plone.contenttypes add-on.',
    id: 'design.plone.contenttypes',
    install_profile_id: 'design.plone.contenttypes:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Design Plone: Content-types',
    uninstall_profile_id: 'design.plone.contenttypes:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '7306',
      newVersion: '7306',
      required: false,
    },
    version: '6.2.18',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/design.plone.policy.limit_root_addables',
    description: 'Installs the design.plone.policy.limit_root_addables add-on',
    id: 'design.plone.policy.limit_root_addables',
    install_profile_id: 'design.plone.policy.limit_root_addables:default',
    is_installed: false,
    profile_type: 'default',
    title: 'design.plone.policy.limit_root_addables',
    uninstall_profile_id: 'design.plone.policy.limit_root_addables:uninstall',
    upgrade_info: {},
    version: '',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/design.plone.policy',
    description: 'Installs the design.plone.policy add-on.',
    id: 'design.plone.policy',
    install_profile_id: 'design.plone.policy:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Design Plone: policy',
    uninstall_profile_id: 'design.plone.policy:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '3103',
      newVersion: '3103',
      required: false,
    },
    version: '5.0.11',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/eea.api.taxonomy',
    description: 'Installs the eea.api.taxonomy add-on.',
    id: 'eea.api.taxonomy',
    install_profile_id: 'eea.api.taxonomy:default',
    is_installed: true,
    profile_type: 'default',
    title: 'eea.api.taxonomy',
    uninstall_profile_id: 'eea.api.taxonomy:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1.0',
      newVersion: '1.0',
      required: false,
    },
    version: '1.5',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/kitconcept.seo',
    description: 'Installa kitconcept.seo',
    id: 'kitconcept.seo',
    install_profile_id: 'kitconcept.seo:default',
    is_installed: true,
    profile_type: 'default',
    title: 'kitconcept.seo',
    uninstall_profile_id: 'kitconcept.seo:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '2.0.1',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/plone.app.iterate',
    description: 'Aggiunge a Plone il supporto alla copia di lavoro.',
    id: 'plone.app.iterate',
    install_profile_id: 'plone.app.iterate:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Copia di lavoro (Working Copy)',
    uninstall_profile_id: 'plone.app.iterate:uninstall',
    upgrade_info: {},
    version: '5.0.5',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/plone.app.multilingual',
    description:
      'Installa per abilitare il supporto multilingua con plone.app.multilingual',
    id: 'plone.app.multilingual',
    install_profile_id: 'plone.app.multilingual:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Supporto Multilingua',
    uninstall_profile_id: 'plone.app.multilingual:uninstall',
    upgrade_info: {},
    version: '7.0.3',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/plone.app.tiles',
    description: 'Basic support for managing tiles',
    id: 'plone.app.tiles',
    install_profile_id: 'plone.app.tiles:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Tiles support',
    uninstall_profile_id: '',
    upgrade_info: {},
    version: '4.0.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/plone.formwidget.autocomplete',
    description: '',
    id: 'plone.formwidget.autocomplete',
    install_profile_id: 'plone.formwidget.autocomplete:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Autocomplete widget',
    uninstall_profile_id: 'plone.formwidget.autocomplete:uninstall',
    upgrade_info: {},
    version: '1.4.1',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/plone.formwidget.contenttree',
    description: '',
    id: 'plone.formwidget.contenttree',
    install_profile_id: 'plone.formwidget.contenttree:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Content tree widget',
    uninstall_profile_id: 'plone.formwidget.contenttree:uninstall',
    upgrade_info: {},
    version: '1.2.0',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/plone.formwidget.geolocation',
    description: 'Extension profile for Plone.',
    id: 'plone.formwidget.geolocation',
    install_profile_id: 'plone.formwidget.geolocation:default',
    is_installed: true,
    profile_type: 'default',
    title: 'plone.formwidget.geolocation map install',
    uninstall_profile_id: 'plone.formwidget.geolocation:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '2000',
      newVersion: '4',
      required: true,
    },
    version: '2.2.1',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/plone.patternslib',
    description: 'Installs the plone.patternslib add-on.',
    id: 'plone.patternslib',
    install_profile_id: 'plone.patternslib:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Plone Patternslib',
    uninstall_profile_id: 'plone.patternslib:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1008',
      newVersion: '1008',
      required: false,
    },
    version: '1.3.0',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/plone.restapi',
    description: 'RESTful hypermedia API for Plone.',
    id: 'plone.restapi',
    install_profile_id: 'plone.restapi:default',
    is_installed: true,
    profile_type: 'default',
    title: 'plone.restapi',
    uninstall_profile_id: 'plone.restapi:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '0007',
      newVersion: '0007',
      required: false,
    },
    version: '9.6.0',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/plone.session',
    description: 'Supporto refresh per plone.session opzionale',
    id: 'plone.session',
    install_profile_id: 'plone.session:default',
    is_installed: false,
    profile_type: 'default',
    title: 'Supporto refresh della sessione',
    uninstall_profile_id: 'plone.session:uninstall',
    upgrade_info: {},
    version: '4.0.4',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/plone.volto',
    description: 'Configura il backend di Plone per lavorare con Volto.',
    id: 'plone.volto',
    install_profile_id: 'plone.volto:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Plone 6 Frontend (plone.volto)',
    uninstall_profile_id: 'plone.volto:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1017',
      newVersion: '1017',
      required: false,
    },
    version: '4.3.0',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/redturtle.bandi',
    description: '',
    id: 'redturtle.bandi',
    install_profile_id: 'redturtle.bandi:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Redturtle: Bandi',
    uninstall_profile_id: 'redturtle.bandi:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '2101',
      newVersion: '2101',
      required: false,
    },
    version: '1.4.3',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/redturtle.faq',
    description: 'Installs the redturtle.faq add-on.',
    id: 'redturtle.faq',
    install_profile_id: 'redturtle.faq:default',
    is_installed: true,
    profile_type: 'default',
    title: 'RedTurtle: Faq',
    uninstall_profile_id: 'redturtle.faq:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.0.2',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/redturtle.volto',
    description: 'Installs the redturtle.volto add-on.',
    id: 'redturtle.volto',
    install_profile_id: 'redturtle.volto:default',
    is_installed: true,
    profile_type: 'default',
    title: 'RedTurtle: Volto',
    uninstall_profile_id: 'redturtle.volto:uninstall',
    upgrade_info: {
      available: true,
      hasProfile: true,
      installedVersion: '4306',
      newVersion: '4307',
      required: true,
    },
    version: '5.5.2',
  },
  {
    '@id':
      'https://v3.io-comune.redturtle.it/api/@addons/redturtle.voltoplugin.editablefooter',
    description: 'Installs the redturtle.voltoplugin.editablefooter add-on.',
    id: 'redturtle.voltoplugin.editablefooter',
    install_profile_id: 'redturtle.voltoplugin.editablefooter:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Volto Editable Footer',
    uninstall_profile_id: 'redturtle.voltoplugin.editablefooter:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1000',
      newVersion: '1000',
      required: false,
    },
    version: '1.3.3',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/rer.newsletter',
    description: 'Installa rer.newsletter',
    id: 'rer.newsletter',
    install_profile_id: 'rer.newsletter:default',
    is_installed: false,
    profile_type: 'default',
    title: 'rer.newsletter',
    uninstall_profile_id: 'rer.newsletter:uninstall',
    upgrade_info: {},
    version: '3.1.0',
  },
  {
    '@id': 'https://v3.io-comune.redturtle.it/api/@addons/souper.plone',
    description: 'Souper Soup Powers for Plone',
    id: 'souper.plone',
    install_profile_id: 'souper.plone:default',
    is_installed: true,
    profile_type: 'default',
    title: 'Soup Storage Foundations and Control Panel',
    uninstall_profile_id: 'souper.plone:uninstall',
    upgrade_info: {
      available: false,
      hasProfile: true,
      installedVersion: '1.0',
      newVersion: '1.0',
      required: false,
    },
    version: '1.3.1',
  },
];
