/// <reference types="react" />
export declare const Controlpanels: any;
export declare const Controlpanel: import("@loadable/component").LoadableComponent<Omit<import("react-intl").WithIntlProps<import("react-intl").WrappedComponentProps<string>>, "ref"> & import("react").RefAttributes<import("react").ComponentType<import("react-intl").WrappedComponentProps<string>>>>;
export declare const RulesControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const AddRuleControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const EditRuleControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const ConfigureRuleControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const UsersControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const RenderUsers: import("@loadable/component").LoadableClassComponent<any>;
export declare const UserGroupMembershipControlPanel: import("@loadable/component").LoadableComponent<unknown>;
export declare const GroupsControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const RenderGroups: import("@loadable/component").LoadableComponent<any>;
export declare const RelationsControlpanel: import("@loadable/component").LoadableComponent<unknown>;
export declare const AliasesControlpanel: import("@loadable/component").LoadableComponent<any>;
export declare const UndoControlpanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const AddonsControlpanel: import("@loadable/component").LoadableComponent<any>;
export declare const ContentType: import("@loadable/component").LoadableClassComponent<any>;
export declare const ContentTypeLayout: import("@loadable/component").LoadableClassComponent<any>;
export declare const ContentTypeSchema: import("@loadable/component").LoadableClassComponent<any>;
export declare const ContentTypes: import("@loadable/component").LoadableClassComponent<any>;
export declare const VersionOverview: import("@loadable/component").LoadableComponent<{
    cmf_version: any;
    debug_mode: any;
    pil_version: any;
    plone_version: any;
    plone_restapi_version: any;
    python_version: any;
    zope_version: any;
}>;
export declare const UpgradeControlPanel: import("@loadable/component").LoadableClassComponent<any>;
export declare const ModerateComments: import("@loadable/component").LoadableClassComponent<any>;
export declare const DatabaseInformation: import("@loadable/component").LoadableComponent<unknown>;
