/*
This file is autogenerated. Don't change it directly.
Instead, change the "addons" setting in your package.json file.
*/

const addonsInfo = [];
export { addonsInfo };

const safeWrapper = (func) => (config) => {
  const res = func(config);
  if (typeof res === 'undefined') {
    throw new Error("Configuration function doesn't return config");
  }
  return res;
};

const projectConfigLoader = false;
const projectConfig = (config) => {
  return projectConfigLoader &&
    typeof projectConfigLoader.default === 'function'
    ? projectConfigLoader.default(config)
    : config;
};

const load = (config) => {
  const addonLoaders = [];
  if (!addonLoaders.every((el) => typeof el === 'function')) {
    throw new TypeError(
      'Each addon has to provide a function applying its configuration to the projects configuration.',
    );
  }
  return projectConfig(
    addonLoaders.reduce((acc, apply) => safeWrapper(apply)(acc), config),
  );
};
export default load;
