import React, { Component } from 'react';
import { Provider } from 'react-redux';
import { StaticRouter } from 'react-router-dom';
import configureStore from 'redux-mock-store';
import { IntlProvider } from 'react-intl';
import thunk from 'redux-thunk';

const initialState = () => ({
  router: {
    location: {
      pathname: '/',
      search: '',
      hash: '',
      key: 'tacrkf',
      query: {},
    },
    action: 'POP',
  },
  intl: {
    defaultLocale: 'en',
    locale: 'en',
    messages: {
      '<p>Add some HTML here</p>': '',
      Accessibility: '',
      'Account Registration Completed': '',
      'Account activation completed': '',
      Action: '',
      Actions: '',
      'Activate and deactivate': '',
      Add: '',
      'Add Addons': '',
      'Add Content': '',
      'Add Translation…': '',
      'Add User': '',
      'Add a description…': '',
      'Add block…': '',
      'Add criteria': '',
      'Add date': '',
      'Add field': '',
      'Add fieldset': '',
      'Add group': '',
      'Add new content type': '',
      'Add new group': '',
      'Add new user': '',
      'Add to Groups': '',
      'Add {type}': '',
      'Add-ons Settings': '',
      'Additional date': '',
      Alignment: '',
      All: '',
      Alphabetically: '',
      'Alt text': '',
      'Are you sure you want to delete this field?': '',
      'Are you sure you want to delete this fieldset including all fields?': '',
      Ascending: '',
      Available: '',
      Back: '',
      Base: '',
      Block: '',
      'Block style': '',
      'Both email address and password are case sensitive, check that caps lock is not enabled.':
        '',
      Breadcrumbs: '',
      Browse: '',
      'Browse the site, drop an image, or type an URL': '',
      'By default, permissions from the container of this item are inherited. If you disable this, only the explicitly defined sharing permissions will be valid. In the overview, the symbol {inherited} indicates an inherited value. Similarly, the symbol {global} indicates a global role, which is managed by the site administrator.':
        '',
      'Cache Name': '',
      "Can not edit Layout for <strong>{type}</strong> content-type as it doesn't have support for <strong>Volto Blocks</strong> enabled":
        '',
      'Can not edit Layout for <strong>{type}</strong> content-type as the <strong>Blocks behavior</strong> is enabled and <strong>read-only</strong>':
        '',
      Cancel: '',
      Cell: '',
      Center: '',
      'Change Note': '',
      'Change Password': '',
      'Change State': '',
      'Change workflow state recursively': '',
      'Changes saved': '',
      'Changes saved.': '',
      Checkbox: '',
      Choices: '',
      'Choose Image': '',
      'Choose Target': '',
      'Click to download full sized image': '',
      Close: '',
      'Close menu': '',
      Collection: '',
      Comment: '',
      Commenter: '',
      Compare: '',
      'Confirm password': '',
      'Connection refused': '',
      Contact: '',
      'Contact form': '',
      'Contained items': '',
      Content: '',
      'Content type created': '',
      'Content type deleted': '',
      Contents: '',
      Copy: '',
      Copyright: '',
      'Copyright statement or other rights information on this item.': '',
      'Created on': '',
      Creator: '',
      Creators: '',
      Criteria: '',
      'Current password': '',
      Cut: '',
      Daily: '',
      'Database Information': '',
      'Database Location': '',
      'Database Size': '',
      'Database main': '',
      Date: '',
      'Date (newest first)': '',
      Default: '',
      Delete: '',
      'Delete Group': '',
      'Delete Type': '',
      'Delete User': '',
      'Delete col': '',
      'Delete row': '',
      Descending: '',
      Description: '',
      Diff: '',
      'Difference between revision {one} and {two} of {title}': '',
      'Distributed under the {license}.': '',
      'Divide each row into separate cells': '',
      'Do you really want to delete the following items?': '',
      'Do you really want to delete the group {groupname}?': '',
      'Do you really want to delete the type {typename}?': '',
      'Do you really want to delete the user {username}?': '',
      'Do you really want to delete this item?': '',
      Document: '',
      'Drag and drop files from your computer onto this area or click the “Browse” button.':
        '',
      'E-mail': '',
      'E-mail addresses do not match.': '',
      Edit: '',
      'Edit comment': '',
      'Edit field': '',
      'Edit fieldset': '',
      'Edit recurrence': '',
      'Edit values': '',
      'Edit {title}': '',
      Email: '',
      'Email sent': '',
      'Embed code error, please follow the instructions and try again.': '',
      'Embeded Google Maps': '',
      'Enable editable Blocks': '',
      'End Date': '',
      'Enter URL or title': '',
      'Enter an email address. This will be your login name. We respect your privacy, and will not give the address away to any third parties or expose it anywhere.':
        '',
      'Enter full name, e.g. John Smith.': '',
      'Enter map Embed Code': '',
      'Enter your current password.': '',
      'Enter your email address for verification.': '',
      'Enter your new password. Minimum 5 characters.': '',
      Error: '',
      'Exclude from navigation': '',
      'Exclude this occurence': '',
      'Excluded from navigation': '',
      'Expand sidebar': '',
      'Expiration Date': '',
      'Expiration date': '',
      Expired: '',
      'External URL': '',
      File: '',
      'File size': '',
      Filename: '',
      'Filter…': '',
      First: '',
      'Fixed width table cells': '',
      Folder: '',
      Forbidden: '',
      Fourth: '',
      From: '',
      Full: '',
      'Full Name': '',
      Fullname: '',
      'GNU GPL license': '',
      'Global role': '',
      'Google Maps Embedded Block': '',
      Group: '',
      'Group created': '',
      Groupname: '',
      Groups: '',
      History: '',
      'History of {title}': '',
      Home: '',
      'Home page': '',
      ID: '',
      'If selected, this item will not appear in the navigation tree': '',
      'If this date is in the future, the content will not show up in listings and searches until this date.':
        '',
      'If you are certain you have the correct web address but are encountering an error, please contact the {site_admin}.':
        '',
      'If you have forgotten your password, {forgotpassword}': '',
      'If you you do not have an account here, head over to the {registrationform}.':
        '',
      Image: '',
      'Include this occurence': '',
      Info: '',
      'Inherit permissions from higher levels': '',
      'Inherited value': '',
      'Insert col after': '',
      'Insert col before': '',
      'Insert row after': '',
      'Insert row before': '',
      Install: '',
      Installed: '',
      'Installed version': '',
      'Interval Daily': '',
      'Interval Monthly': '',
      'Interval Weekly': '',
      'Interval Yearly': '',
      'Item batch size': '',
      'Item(s) copied.': '',
      'Item(s) cut.': '',
      'Item(s) pasted.': '',
      Items: '',
      'Items must be unique.': '',
      Language: '',
      Last: '',
      'Last comment date': '',
      'Last modified': '',
      'Latest version': '',
      Layout: '',
      'Lead Image': '',
      Left: '',
      Link: '',
      'Link more': '',
      'Link title': '',
      'Link to': '',
      Listing: '',
      Location: '',
      'Log In': '',
      'Log in': '',
      Login: '',
      'Login Failed': '',
      'Login Name': '',
      'Make the table compact': '',
      Map: '',
      'Maps URL': '',
      'Maximum length is {len}.': '',
      'Maximum value is {len}.': '',
      Message: '',
      'Minimum length is {len}.': '',
      'Minimum value is {len}.': '',
      'Moderate Comments': '',
      'Moderate comments': '',
      'Monday and Friday': '',
      'Month day': '',
      Monthly: '',
      More: '',
      'Move to bottom of folder': '',
      'Move to top of folder': '',
      'My email address is': '',
      Name: '',
      'Navigate back': '',
      'New password': '',
      'News Item': '',
      No: '',
      'No image selected': '',
      'No image set in Lead Image content field': '',
      'No image set in image content field': '',
      'No items found in this container.': '',
      'No items selected': '',
      'No map selected': '',
      'No occurences set': '',
      'No options': '',
      'No results found': '',
      'No results found.': '',
      'No selection': '',
      'No uninstall profile': '',
      'No value': '',
      'No video selected': '',
      'No workflow': '',
      None: '',
      'Number of active objects': '',
      'Object Size': '',
      Occurences: '',
      Ok: '',
      'Open in a new tab': '',
      'Open menu': '',
      Origin: '',
      Page: '',
      'Parent fieldset': '',
      Password: '',
      'Password reset': '',
      'Passwords do not match.': '',
      Paste: '',
      'Personal Information': '',
      'Personal Preferences': '',
      'Personal tools': '',
      'Persons responsible for creating the content of this item. Please enter a list of user names, one per line. The principal creator should come first.':
        '',
      'Please enter a valid URL by deleting the block and adding a new video block.':
        '',
      'Please enter the Embed Code provided by Google Maps -> Share -> Embed map. It should contain the <iframe> code on it.':
        '',
      'Please fill out the form below to set your password.': '',
      'Plone Foundation': '',
      'Plone Site': '',
      'Plone{reg} Open Source CMS/WCM': '',
      Portrait: '',
      'Possible values': '',
      'Powered by Plone & Python': '',
      Preferences: '',
      Preview: '',
      Profile: '',
      Properties: '',
      'Publication date': '',
      'Publishing Date': '',
      'Re-enter the password. Make sure the passwords are identical.': '',
      'Read More…': '',
      'Rearrange items by…': '',
      'Recurrence ends': '',
      'Recurrence ends after': '',
      'Recurrence ends on': '',
      'Reduce complexity': '',
      Register: '',
      'Registration form': '',
      Relevance: '',
      'Remove recurrence': '',
      Rename: '',
      'Rename items': '',
      Repeat: '',
      'Repeat every': '',
      'Repeat on': '',
      Required: '',
      'Required input is missing.': '',
      'Results limit': '',
      'Results preview': '',
      'Reversed order': '',
      'Revert to this revision': '',
      'Review state': '',
      Richtext: '',
      Right: '',
      Rights: '',
      Roles: '',
      Save: '',
      'Save recurrence': '',
      Schema: '',
      'Schema updates': '',
      Search: '',
      'Search Site': '',
      'Search content': '',
      'Search for user or group': '',
      'Search group…': '',
      'Search results': '',
      'Search results for {term}': '',
      'Search users…': '',
      Second: '',
      'Select a date to add to recurrence': '',
      'Select columns to show': '',
      'Select criteria': '',
      'Select the transition to be used for modifying the items state.': '',
      'Selected dates': '',
      'Selected items': '',
      'Selected items - x of y': '',
      Selection: '',
      'Select…': '',
      Send: '',
      'Set my password': '',
      'Set your password': '',
      Settings: '',
      Sharing: '',
      'Sharing for {title}': '',
      'Short Name': '',
      'Short name': '',
      Show: '',
      'Shrink sidebar': '',
      'Shrink toolbar': '',
      'Sign in to start session': '',
      Site: '',
      'Site Administration': '',
      'Site Map': '',
      'Site Setup': '',
      Sitemap: '',
      Size: '',
      'Size: {size}': '',
      'Sorry, something went wrong with your request': '',
      'Sort By:': '',
      'Sort on': '',
      Source: '',
      'Specify a youtube video or playlist url': '',
      Split: '',
      'Start Date': '',
      'Start of the recurrence': '',
      'Start password reset': '',
      State: '',
      String: '',
      'Stripe alternate rows with color': '',
      Subject: '',
      Success: '',
      Table: '',
      'Table color inverted': '',
      'Table of Contents': '',
      Tags: '',
      'Tags to add': '',
      'Tags to remove': '',
      'Target memory size per cache in bytes': '',
      'Target number of objects in memory per cache': '',
      Template: '',
      Text: '',
      'Thank you.': '',
      'The Database Manager allow you to view database status information': '',
      'The URL for your external home page, if you have one.': '',
      "The backend is not responding, please check if you have started Plone, check your project's configuration object apiPath (or if you are using the internal proxy, devProxyToApiPath) or the RAZZLE_API_PATH Volto's environment variable.":
        '',
      'The backend is responding, but the CORS headers are not configured properly and the browser has denied the access to the backend resources.':
        '',
      'The backend server of your website is not anwering, we apologize for the inconvenience. Please try to re-load the page and try again. If the problem persists please contact the site administrators.':
        '',
      'The registration process has been successful. Please check your e-mail inbox for information on how activate your account.':
        '',
      'The user portrait/avatar': '',
      'The {plonecms} is {copyright} 2000-{current_year} by the {plonefoundation} and friends.':
        '',
      'There is a configuration problem on the backend': '',
      'There were some errors': '',
      'There were some errors.': '',
      Third: '',
      'This name will be displayed in the URL.': '',
      'This page does not seem to exist…': '',
      Time: '',
      Title: '',
      'Total active and non-active objects': '',
      'Total comments': '',
      'Total number of objects in each cache': '',
      'Total number of objects in memory from all caches': '',
      'Total number of objects in the database': '',
      'Translate to {lang}': '',
      Type: '',
      'Type a Video (YouTube, Vimeo or mp4) URL': '',
      'Type text…': '',
      'Type the title…': '',
      UID: '',
      Unauthorized: '',
      Unified: '',
      Uninstall: '',
      'Unknown Block': 'Unknown Block {block}',
      Update: '',
      'Update installed addons': '',
      'Update installed addons:': '',
      'Updates available': '',
      Upload: '',
      "Upload a lead image in the 'Lead Image' content field.": '',
      'Upload a new image': '',
      'Upload files': '',
      'Upload {count, plural, one {# file} other {# files}}': '',
      'Uploading files': '',
      'Used for programmatic access to the fieldset.': '',
      User: '',
      'User created': '',
      'User name': '',
      Username: '',
      Users: '',
      'Users and Groups': '',
      'Users and groups settings': '',
      'Version Overview': '',
      Video: '',
      'Video URL': '',
      View: '',
      'View changes': '',
      'View this revision': '',
      Viewmode: '',
      'Warning Regarding debug mode': '',
      'We apologize for the inconvenience, but the backend of the site you are accessing is not available right now. Please, try again later.':
        '',
      'We apologize for the inconvenience, but the page you were trying to access is not at this address. You can use the links below to help you find what you are looking for.':
        '',
      "We apologize for the inconvenience, but you don't have permissions on this resource.":
        '',
      'We will use this address if you need to recover your password': '',
      'Weeek day of month': '',
      Weekday: '',
      Weekly: '',
      What: '',
      When: '',
      'When this date is reached, the content will nolonger be visible in listings and searches.':
        '',
      Who: '',
      'Workflow updated.': '',
      Yearly: '',
      Yes: '',
      'You are trying to access a protected resource, please {login} first.':
        '',
      'You are using an outdated browser': '',
      'You can add a comment by filling out the form below. Plain text formatting.':
        '',
      'You can control who can view and edit your item using the list below.':
        '',
      'You can view the difference of the revisions below.': '',
      'You can view the history of your item below.': '',
      'Your email is required for reset your password.': '',
      'Your location - either city and country - or in a company setting, where your office is located.':
        '',
      'Your password has been set successfully. You may now {link} with your new password.':
        '',
      'Your preferred language': '',
      box_forgot_password_option: '',
      common: '',
      delete: '',
      deprecated_browser_notice_message: '',
      description: '',
      description_lost_password: '',
      description_sent_password: '',
      draft: '',
      email: '',
      event_alldates: '',
      event_attendees: '',
      event_contactname: '',
      event_contactphone: '',
      event_website: '',
      event_what: '',
      event_when: '',
      event_where: '',
      heading_sent_password: '',
      hero: '',
      html: '',
      image: '',
      integer: '',
      intranet: '',
      label_my_email_address_is: '',
      leadimage: '',
      listing: '',
      'log in': '',
      maps: '',
      maxLength: '',
      maximum: '',
      media: '',
      minLength: '',
      minimum: '',
      mostUsed: '',
      'no workflow state': '',
      number: '',
      'of the month': '',
      'or try a different page.': '',
      others: '',
      private: '',
      published: '',
      'querystring-widget-select': '',
      'registration form': '',
      'results found': '',
      'return to the site root': '',
      rrule_and: '',
      rrule_approximate: '',
      rrule_at: '',
      rrule_dateFormat: '',
      rrule_day: '',
      rrule_days: '',
      rrule_every: '',
      rrule_for: '',
      rrule_hour: '',
      rrule_hours: '',
      rrule_in: '',
      rrule_last: '',
      rrule_minutes: '',
      rrule_month: '',
      rrule_months: '',
      rrule_nd: '',
      rrule_on: '',
      'rrule_on the': '',
      rrule_or: '',
      rrule_rd: '',
      rrule_st: '',
      rrule_th: '',
      rrule_the: '',
      rrule_time: '',
      rrule_times: '',
      rrule_until: '',
      rrule_week: '',
      rrule_weekday: '',
      rrule_weekdays: '',
      rrule_weeks: '',
      rrule_year: '',
      rrule_years: '',
      sort: '',
      table: '',
      text: '',
      title: '',
      toc: '',
      url: '',
      'user avatar': '',
      video: '',
      visit_external_website: '',
      'we can send you a new one': '',
      '{count} selected': '',
      '{id} Content Type': '',
      '{id} Schema': '',
      '{title} copied.': '',
      '{title} cut.': '',
      '{title} has been deleted.': '',
      '{user} says:': '',
    },
  },
  reduxAsyncConnect: {
    loaded: true,
    loadState: {
      breadcrumbs: {
        loading: false,
        loaded: true,
        error: null,
      },
      content: {
        loading: false,
        loaded: true,
        error: null,
      },
      navigation: {
        loading: false,
        loaded: true,
        error: null,
      },
      workflow: {
        loading: false,
        loaded: true,
        error: null,
      },
    },
    breadcrumbs: {
      '@id': 'http://localhost:3000/api/@breadcrumbs',
      items: [],
    },
    content: {
      '@components': {
        actions: {
          '@id': 'http://localhost:3000/api/@actions',
        },
        breadcrumbs: {
          '@id': 'http://localhost:3000/api/@breadcrumbs',
        },
        navigation: {
          '@id': 'http://localhost:3000/api/@navigation',
        },
      },
      '@id': 'http://localhost:3000/api/',
      '@type': 'Plone Site',
      blocks: {
        '0358abe2-b4f1-463d-a279-a63ea80daf19': {
          '@type': 'description',
        },
        '07c273fc-8bfc-4e7d-a327-d513e5a945bb': {
          '@type': 'title',
        },
        '2dfe8e4c-5bf6-43f1-93e1-6c320ede7226': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 10,
                    offset: 0,
                    style: 'BOLD',
                  },
                ],
                key: '6470b',
                text:
                  'Disclaimer: This instance is reset every night, so all changes will be lost afterwards.',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        '3c881f51-f75b-4959-834a-6e1d5edc32ae': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 5,
                    offset: 6,
                    style: 'BOLD',
                  },
                ],
                key: 'ekn3l',
                text: 'user: admin',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        '5e1c30b1-ec6c-4dc0-9483-9768c3c416e4': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 5,
                    offset: 0,
                  },
                  {
                    key: 1,
                    length: 8,
                    offset: 455,
                  },
                ],
                inlineStyleRanges: [],
                key: 'behki',
                text:
                  'Plone is a CMS built on Python with over 19 years of experience. Plone has very interesting features that appeal to developers and users alike, such as customizable content types, hierarchical URL object traversing and a sophisticated content workflow powered by a granular permissions model. This allows you to build anything from simple websites to enterprise-grade intranets. Volto exposes all these features and communicates with Plone via its mature REST API. Volto can be esily themed and is highly customizable.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://plone.org',
                  rel: 'nofollow',
                  url: 'https://plone.org/',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
              '1': {
                data: {
                  href: 'https://github.com/plone/plone.restapi',
                  url: 'https://github.com/plone/plone.restapi',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
        '61cc1bc0-d4f5-4e2b-9152-79512045a4dd': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: '9qsa4',
                text: 'Demo',
                type: 'header-two',
              },
            ],
            entityMap: {},
          },
        },
        '874049e7-629e-489a-b46c-1adf35ad40ee': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: '9pnjr',
                text: 'Happy hacking!',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        '942b6530-2407-420f-9c24-597adda6b2ce': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 36,
                    offset: 39,
                  },
                ],
                inlineStyleRanges: [],
                key: '6a248',
                text:
                  'Last but not least, it also supports a Volto Nodejs-based backend reference API implementation that demos how other systems could also use Volto to display and create content through it.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://github.com/plone/volto-reference-backend',
                  url: 'https://github.com/plone/volto-reference-backend',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
        '9a976b8e-72ba-468a-bea8-b37a31bb386b': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 12,
                    offset: 51,
                    style: 'BOLD',
                  },
                ],
                key: '94arl',
                text:
                  'You can log in and use it as admin user using these credentials:',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'b3717238-448f-406e-b06f-57a9715c3326': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 5,
                    offset: 0,
                  },
                ],
                inlineStyleRanges: [],
                key: '1bnna',
                text:
                  'Volto is a React-based frontend for content management systems, currently supporting three backend implementations: Plone, Guillotina and a NodeJS reference implementation.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://github.com/plone/volto',
                  url: 'https://github.com/plone/volto',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
        'c049ff8b-3e5a-4cfb-bca6-e4a6cca9be28': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: '55n44',
                text:
                  'You can use this site to test Volto. It runs on the master branch of Volto using latest Plone 5.2 Backend running on Python 3.',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'c91f0fe9-f2e9-4a17-84a5-8e4f2678ed3c': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 5,
                    offset: 10,
                    style: 'BOLD',
                  },
                ],
                key: 'buncq',
                text: 'password: admin',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'e0ca2fbc-7800-4b9b-afe5-8e42af9f5dd6': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: 'f0prj',
                text: '2020 - Volto Team - Plone Foundation',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'effbdcdc-253c-41a7-841e-5edb3b56ce32': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 10,
                    offset: 36,
                  },
                ],
                inlineStyleRanges: [],
                key: '68rve',
                text:
                  'Volto also supports other APIs like Guillotina, a Python resource management system, inspired by Plone and using the same basic concepts like traversal, content types and permissions model.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://guillotina.io/',
                  rel: 'nofollow',
                  url: 'https://guillotina.io/',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
      },
      blocks_layout: {
        items: [
          '07c273fc-8bfc-4e7d-a327-d513e5a945bb',
          '0358abe2-b4f1-463d-a279-a63ea80daf19',
          'b3717238-448f-406e-b06f-57a9715c3326',
          '5e1c30b1-ec6c-4dc0-9483-9768c3c416e4',
          'effbdcdc-253c-41a7-841e-5edb3b56ce32',
          '942b6530-2407-420f-9c24-597adda6b2ce',
          '61cc1bc0-d4f5-4e2b-9152-79512045a4dd',
          'c049ff8b-3e5a-4cfb-bca6-e4a6cca9be28',
          '9a976b8e-72ba-468a-bea8-b37a31bb386b',
          '3c881f51-f75b-4959-834a-6e1d5edc32ae',
          'c91f0fe9-f2e9-4a17-84a5-8e4f2678ed3c',
          '2dfe8e4c-5bf6-43f1-93e1-6c320ede7226',
          '874049e7-629e-489a-b46c-1adf35ad40ee',
          'e0ca2fbc-7800-4b9b-afe5-8e42af9f5dd6',
        ],
      },
      description: 'The React powered content management system',
      id: 'Plone',
      is_folderish: true,
      items: [
        {
          '@id': 'http://localhost:3000/api/front-page',
          '@type': 'Document',
          description:
            'Congratulations! You have successfully installed Plone.',
          review_state: 'published',
          title: 'Welcome to Plone',
        },
        {
          '@id': 'http://localhost:3000/api/news',
          '@type': 'Folder',
          description: 'Site News',
          review_state: 'published',
          title: 'News',
        },
        {
          '@id': 'http://localhost:3000/api/events',
          '@type': 'Folder',
          description: 'Site Events',
          review_state: 'published',
          title: 'Events',
        },
        {
          '@id': 'http://localhost:3000/api/Members',
          '@type': 'Folder',
          description: 'Site Users',
          review_state: 'private',
          title: 'Users',
        },
      ],
      items_total: 4,
      parent: {},
      title: 'Welcome to Volto!',
    },
    navigation: {
      '@id': 'http://localhost:3000/api/@navigation',
      items: [
        {
          '@id': 'http://localhost:3000/api',
          description: '',
          title: 'Home',
        },
        {
          '@id': 'http://localhost:3000/api/news',
          description: 'Site News',
          title: 'News',
        },
        {
          '@id': 'http://localhost:3000/api/events',
          description: 'Site Events',
          title: 'Events',
        },
        {
          '@id': 'http://localhost:3000/api/Members',
          description: 'Site Users',
          title: 'Users',
        },
      ],
    },
    workflow: {
      '@id': 'http://localhost:3000/api/@workflow',
      history: [],
      transitions: [],
    },
  },
  actions: {
    error: null,
    actions: {
      document_actions: [],
      object: [
        {
          icon: '',
          id: 'view',
          title: 'View',
        },
        {
          icon: '',
          id: 'edit',
          title: 'Edit',
        },
        {
          icon: '',
          id: 'folderContents',
          title: 'Contents',
        },
        {
          icon: '',
          id: 'history',
          title: 'History',
        },
        {
          icon: '',
          id: 'local_roles',
          title: 'Sharing',
        },
      ],
      object_buttons: [],
      portal_tabs: [
        {
          icon: '',
          id: 'index_html',
          title: 'Home',
        },
      ],
      site_actions: [
        {
          icon: '',
          id: 'sitemap',
          title: 'Site Map',
        },
        {
          icon: '',
          id: 'accessibility',
          title: 'Accessibility',
        },
        {
          icon: '',
          id: 'contact',
          title: 'Contact',
        },
      ],
      user: [
        {
          icon: '',
          id: 'preferences',
          title: 'Preferences',
        },
        {
          icon: '',
          id: 'dashboard',
          title: 'Dashboard',
        },
        {
          icon: '',
          id: 'plone_setup',
          title: 'Site Setup',
        },
        {
          icon: '',
          id: 'logout',
          title: 'Log out',
        },
      ],
    },
    loaded: true,
    loading: false,
  },
  addons: {
    error: null,
    installedAddons: [],
    availableAddons: [],
    upgradableAddons: [],
    loaded: false,
    loading: false,
  },
  apierror: {
    error: null,
    statusCode: null,
    connectionRefused: false,
    message: null,
  },
  breadcrumbs: {
    error: null,
    items: [
      {
        title: 'Hello',
        url: '/hello',
      },
      {
        title: 'world',
        url: '/hello/world',
      },
    ],
    loaded: true,
    loading: false,
  },
  browserdetect: {
    name: 'chrome',
    version: '85.0.4183',
    os: 'Windows 10',
    type: 'browser',
  },
  comments: {
    add: {
      loaded: false,
      loading: false,
      error: null,
    },
    delete: {
      loaded: false,
      loading: false,
      error: null,
    },
    update: {
      loaded: false,
      loading: false,
      error: null,
    },
    list: {
      loaded: false,
      loading: false,
      error: null,
    },
    items: [],
  },
  content: {
    create: {
      loaded: false,
      loading: false,
      error: null,
    },
    delete: {
      loaded: false,
      loading: false,
      error: null,
    },
    update: {
      loaded: false,
      loading: false,
      error: null,
    },
    get: {
      loading: false,
      loaded: true,
      error: null,
    },
    order: {
      loaded: false,
      loading: false,
      error: null,
    },
    data: {
      '@components': {
        actions: {
          '@id': 'http://localhost:3000/api/@actions',
        },
        breadcrumbs: {
          '@id': 'http://localhost:3000/api/@breadcrumbs',
        },
        navigation: {
          '@id': 'http://localhost:3000/api/@navigation',
        },
      },
      '@id': 'http://localhost:3000/api/',
      '@type': 'Plone Site',
      blocks: {
        '0358abe2-b4f1-463d-a279-a63ea80daf19': {
          '@type': 'description',
        },
        '07c273fc-8bfc-4e7d-a327-d513e5a945bb': {
          '@type': 'title',
        },
        '2dfe8e4c-5bf6-43f1-93e1-6c320ede7226': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 10,
                    offset: 0,
                    style: 'BOLD',
                  },
                ],
                key: '6470b',
                text:
                  'Disclaimer: This instance is reset every night, so all changes will be lost afterwards.',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        '3c881f51-f75b-4959-834a-6e1d5edc32ae': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 5,
                    offset: 6,
                    style: 'BOLD',
                  },
                ],
                key: 'ekn3l',
                text: 'user: admin',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        '5e1c30b1-ec6c-4dc0-9483-9768c3c416e4': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 5,
                    offset: 0,
                  },
                  {
                    key: 1,
                    length: 8,
                    offset: 455,
                  },
                ],
                inlineStyleRanges: [],
                key: 'behki',
                text:
                  'Plone is a CMS built on Python with over 19 years of experience. Plone has very interesting features that appeal to developers and users alike, such as customizable content types, hierarchical URL object traversing and a sophisticated content workflow powered by a granular permissions model. This allows you to build anything from simple websites to enterprise-grade intranets. Volto exposes all these features and communicates with Plone via its mature REST API. Volto can be esily themed and is highly customizable.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://plone.org',
                  rel: 'nofollow',
                  url: 'https://plone.org/',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
              '1': {
                data: {
                  href: 'https://github.com/plone/plone.restapi',
                  url: 'https://github.com/plone/plone.restapi',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
        '61cc1bc0-d4f5-4e2b-9152-79512045a4dd': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: '9qsa4',
                text: 'Demo',
                type: 'header-two',
              },
            ],
            entityMap: {},
          },
        },
        '874049e7-629e-489a-b46c-1adf35ad40ee': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: '9pnjr',
                text: 'Happy hacking!',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        '942b6530-2407-420f-9c24-597adda6b2ce': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 36,
                    offset: 39,
                  },
                ],
                inlineStyleRanges: [],
                key: '6a248',
                text:
                  'Last but not least, it also supports a Volto Nodejs-based backend reference API implementation that demos how other systems could also use Volto to display and create content through it.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://github.com/plone/volto-reference-backend',
                  url: 'https://github.com/plone/volto-reference-backend',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
        '9a976b8e-72ba-468a-bea8-b37a31bb386b': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 12,
                    offset: 51,
                    style: 'BOLD',
                  },
                ],
                key: '94arl',
                text:
                  'You can log in and use it as admin user using these credentials:',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'b3717238-448f-406e-b06f-57a9715c3326': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 5,
                    offset: 0,
                  },
                ],
                inlineStyleRanges: [],
                key: '1bnna',
                text:
                  'Volto is a React-based frontend for content management systems, currently supporting three backend implementations: Plone, Guillotina and a NodeJS reference implementation.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://github.com/plone/volto',
                  url: 'https://github.com/plone/volto',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
        'c049ff8b-3e5a-4cfb-bca6-e4a6cca9be28': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: '55n44',
                text:
                  'You can use this site to test Volto. It runs on the master branch of Volto using latest Plone 5.2 Backend running on Python 3.',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'c91f0fe9-f2e9-4a17-84a5-8e4f2678ed3c': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [
                  {
                    length: 5,
                    offset: 10,
                    style: 'BOLD',
                  },
                ],
                key: 'buncq',
                text: 'password: admin',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'e0ca2fbc-7800-4b9b-afe5-8e42af9f5dd6': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [],
                inlineStyleRanges: [],
                key: 'f0prj',
                text: '2020 - Volto Team - Plone Foundation',
                type: 'unstyled',
              },
            ],
            entityMap: {},
          },
        },
        'effbdcdc-253c-41a7-841e-5edb3b56ce32': {
          '@type': 'text',
          text: {
            blocks: [
              {
                data: {},
                depth: 0,
                entityRanges: [
                  {
                    key: 0,
                    length: 10,
                    offset: 36,
                  },
                ],
                inlineStyleRanges: [],
                key: '68rve',
                text:
                  'Volto also supports other APIs like Guillotina, a Python resource management system, inspired by Plone and using the same basic concepts like traversal, content types and permissions model.',
                type: 'unstyled',
              },
            ],
            entityMap: {
              '0': {
                data: {
                  href: 'https://guillotina.io/',
                  rel: 'nofollow',
                  url: 'https://guillotina.io/',
                },
                mutability: 'MUTABLE',
                type: 'LINK',
              },
            },
          },
        },
      },
      blocks_layout: {
        items: [
          '07c273fc-8bfc-4e7d-a327-d513e5a945bb',
          '0358abe2-b4f1-463d-a279-a63ea80daf19',
          'b3717238-448f-406e-b06f-57a9715c3326',
          '5e1c30b1-ec6c-4dc0-9483-9768c3c416e4',
          'effbdcdc-253c-41a7-841e-5edb3b56ce32',
          '942b6530-2407-420f-9c24-597adda6b2ce',
          '61cc1bc0-d4f5-4e2b-9152-79512045a4dd',
          'c049ff8b-3e5a-4cfb-bca6-e4a6cca9be28',
          '9a976b8e-72ba-468a-bea8-b37a31bb386b',
          '3c881f51-f75b-4959-834a-6e1d5edc32ae',
          'c91f0fe9-f2e9-4a17-84a5-8e4f2678ed3c',
          '2dfe8e4c-5bf6-43f1-93e1-6c320ede7226',
          '874049e7-629e-489a-b46c-1adf35ad40ee',
          'e0ca2fbc-7800-4b9b-afe5-8e42af9f5dd6',
        ],
      },
      description: 'The React powered content management system',
      id: 'Plone',
      is_folderish: true,
      items: [
        {
          '@id': 'http://localhost:3000/api/front-page',
          '@type': 'Document',
          description:
            'Congratulations! You have successfully installed Plone.',
          review_state: 'published',
          title: 'Welcome to Plone',
          url: '/front-page',
        },
        {
          '@id': 'http://localhost:3000/api/news',
          '@type': 'Folder',
          description: 'Site News',
          review_state: 'published',
          title: 'News',
          url: '/news',
        },
        {
          '@id': 'http://localhost:3000/api/events',
          '@type': 'Folder',
          description: 'Site Events',
          review_state: 'published',
          title: 'Events',
          url: '/events',
        },
        {
          '@id': 'http://localhost:3000/api/Members',
          '@type': 'Folder',
          description: 'Site Users',
          review_state: 'private',
          title: 'Users',
          url: '/Members',
        },
      ],
      items_total: 4,
      parent: {},
      title: 'Welcome to Volto!',
    },
    subrequests: {},
  },
  controlpanels: {
    get: {
      loaded: false,
      loading: false,
      error: null,
    },
    list: {
      loaded: false,
      loading: false,
      error: null,
    },
    update: {
      loaded: false,
      loading: false,
      error: null,
    },
    post: {
      loaded: false,
      loading: false,
      error: null,
    },
    delete: {
      loaded: false,
      loading: false,
      error: null,
    },
    controlpanel: null,
    controlpanels: [],
    systeminformation: null,
    databaseinformation: null,
  },
  clipboard: {
    action: null,
    source: null,
    request: {
      loaded: false,
      loading: false,
      error: null,
    },
  },
  diff: {
    error: null,
    data: [],
    loaded: false,
    loading: false,
  },
  emailNotification: {
    error: null,
    loaded: false,
    loading: false,
  },
  form: {},
  groups: {
    create: {
      loaded: false,
      loading: false,
      error: null,
    },
    delete: {
      loaded: false,
      loading: false,
      error: null,
    },
    get: {
      loaded: false,
      loading: false,
      error: null,
    },
    list: {
      loaded: false,
      loading: false,
      error: null,
    },
    update: {
      loaded: false,
      loading: false,
      error: null,
    },
    groups: [],
    group: {},
  },
  history: {
    entries: [],
    get: {
      error: null,
      loaded: false,
      loading: false,
    },
    revert: {
      error: null,
      loaded: false,
      loading: false,
    },
  },
  messages: {
    messages: [],
  },
  navigation: {
    error: null,
    items: [
      {
        title: 'Home',
        url: '',
      },
      {
        title: 'News',
        url: '/news',
      },
      {
        title: 'Events',
        url: '/events',
      },
      {
        title: 'Users',
        url: '/Members',
      },
    ],
    loaded: true,
    loading: false,
  },
  querystring: {
    error: null,
    indexes: {},
    sortable_indexes: {},
    loaded: false,
    loading: false,
  },
  querystringsearch: {
    error: null,
    items: [],
    total: 0,
    loaded: false,
    loading: false,
    batching: {},
    subrequests: {},
  },
  roles: {
    error: null,
    roles: [],
    loaded: false,
    loading: false,
  },
  schema: {
    error: null,
    loaded: false,
    loading: false,
    schema: null,
    post: {
      loaded: false,
      loading: false,
      error: null,
    },
    update: {
      loaded: false,
      loading: false,
      error: null,
    },
    put: {
      loaded: false,
      loading: false,
      error: null,
    },
  },
  search: {
    error: null,
    items: [],
    total: 0,
    loaded: false,
    loading: false,
    batching: {},
    subrequests: {},
  },
  sharing: {
    update: {
      loaded: false,
      loading: false,
      error: null,
    },
    get: {
      loaded: false,
      loading: false,
      error: null,
    },
    data: {
      available_roles: [],
      entries: [],
      inherit: null,
    },
  },
  sidebar: {
    tab: 0,
  },
  types: {
    error: null,
    loaded: true,
    loading: false,
    types: [
      {
        '@id': 'http://localhost:3000/api/@types/Collection',
        addable: true,
        title: 'Collection',
      },
      {
        '@id': 'http://localhost:3000/api/@types/Event',
        addable: true,
        title: 'Event',
      },
      {
        '@id': 'http://localhost:3000/api/@types/File',
        addable: true,
        title: 'File',
      },
      {
        '@id': 'http://localhost:3000/api/@types/Folder',
        addable: true,
        title: 'Folder',
      },
      {
        '@id': 'http://localhost:3000/api/@types/Image',
        addable: true,
        title: 'Image',
      },
      {
        '@id': 'http://localhost:3000/api/@types/LRF',
        addable: false,
        title: 'LRF',
      },
      {
        '@id': 'http://localhost:3000/api/@types/Link',
        addable: true,
        title: 'Link',
      },
      {
        '@id': 'http://localhost:3000/api/@types/News Item',
        addable: true,
        title: 'News Item',
      },
      {
        '@id': 'http://localhost:3000/api/@types/Document',
        addable: true,
        title: 'Page',
      },
    ],
  },
  users: {
    user: {},
    users: [],
    create: {
      error: null,
      loaded: false,
      loading: false,
    },
    get: {
      error: null,
      loaded: false,
      loading: false,
    },
    list: {
      error: null,
      loaded: false,
      loading: false,
    },
    delete: {
      error: null,
      loaded: false,
      loading: false,
    },
    update: {
      error: null,
      loaded: false,
      loading: false,
    },
    update_password: {
      error: null,
      loaded: false,
      loading: false,
    },
    password: {
      error: null,
      loaded: false,
      loading: false,
    },
    initial: {
      error: null,
      loaded: false,
      loading: false,
    },
    reset: {
      error: null,
      loaded: false,
      loading: false,
    },
  },
  userSession: {
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYwMDY1NTM1OSwiZnVsbG5hbWUiOm51bGx9.G7vqPxmRTQkJkLlRoUFZIJRJqdjjKcc9Ymacty9_h0g',
    login: {
      loaded: false,
      loading: false,
      error: null,
    },
  },
  vocabularies: {},
  workflow: {
    get: {
      loading: false,
      loaded: true,
      error: null,
    },
    transition: {
      loaded: false,
      loading: false,
      error: null,
    },
    history: [],
    transitions: [],
    multiple: [],
  },
  toolbar: {
    expanded: true,
  },
});

export default class Wrapper extends Component {
  customState() {
    let state = initialState();
    if (this.props.anonymous) {
      state.userSession.token = null;
    }
    if (this.props.customStore) {
      state = {
        ...state,
        ...this.props.customStore,
      };
    }
    return state;
  }

  render() {
    // If thunk is not included there's a complaint about async actions
    const store = configureStore([thunk])(this.customState());
    return (
      <Provider store={store}>
        <IntlProvider locale="en">
          <StaticRouter location={this.props.location}>
            <div className="volto-rsg-container">{this.props.children}</div>
          </StaticRouter>
        </IntlProvider>
      </Provider>
    );
  }
}
