import fs from 'fs';
import path from 'path';
import cryptoRandomString from 'crypto-random-string';
import { AddonRegistry } from '@plone/registry/addon-registry';
import { createAddonsLoader } from '@plone/registry/create-addons-loader';
import { createAddonsServerLoader } from '@plone/registry/create-addons-loader-server';
import { createThemeAddonsLoader } from '@plone/registry/create-theme-loader';
import { createAddonsStyleLoader } from '@plone/registry/create-addons-styles-loader';
import { createAddonsLocalesLoader } from '@plone/registry/create-addons-locales-loader';
import { pathToFileURL } from 'node:url';

const titleCase = (w) => w.slice(0, 1).toUpperCase() + w.slice(1, w.length);

function nameFromPath(filePath) {
  const normalizedPath =
    filePath.replace(/[@~./\\:\s-]/gi, '') ||
    cryptoRandomString({ length: 10, characters: 'abcdefghijk' });

  return normalizedPath
    .split('-')
    .map((w, i) => (i > 0 ? titleCase(w) : w))
    .join('');
}

function getAddonViteExtenders(registry) {
  return registry
    .getAddons()
    .map((addon) => {
      const base = path.dirname(addon.packageJson);
      const viteExtendJs = path.resolve(`${base}/vite.extend.js`);
      const viteExtendTs = path.resolve(`${base}/vite.extend.ts`);

      if (fs.existsSync(viteExtendJs)) return viteExtendJs;
      if (fs.existsSync(viteExtendTs)) return viteExtendTs;
      return null;
    })
    .filter(Boolean);
}

function createViteLoader(extenders) {
  const viteLoaderPath = path.join(process.cwd(), '.plone', 'vite.loader.js');

  let code = `/*
Don't change this file manually.
It is autogenerated by @plone/registry.
Instead, change the "addons" registration in the app.
*/\n`;

  const extendersToLoad = [];

  extenders.forEach((extenderPath) => {
    const defaultImport = nameFromPath(extenderPath);
    const fileUrl = pathToFileURL(extenderPath).href;
    code += `import ${defaultImport} from '${fileUrl}';\n`;
    extendersToLoad.push(defaultImport);
  });

  code += `
const safeWrapper = (func) => (config, context) => {
  const res = func(config, context);
  if (typeof res === 'undefined') {
    throw new Error("Vite extension function doesn't return config");
  }
  return res;
};

const load = (config, context = {}) => {
  const addonLoaders = [${extendersToLoad.join(', ')}];
  if (!addonLoaders.every((el) => typeof el === 'function')) {
    throw new TypeError(
      'Each addon has to provide a function applying its Vite extension to the app configuration.',
    );
  }
  return addonLoaders.reduce(
    (acc, apply) => safeWrapper(apply)(acc, context),
    config,
  );
};
export default load;
`;

  fs.writeFileSync(viteLoaderPath, code);
  return viteLoaderPath;
}

export function relativeToAbsoluteImportPlugin(options) {
  const { packages } = options;

  const entries = Object.entries(packages);

  return {
    name: 'relative-to-absolute-imports',
    enforce: 'pre',

    async transform(code, id) {
      const normalizedId = id.split('?')[0];

      const match = entries.find(([, pkgInfo]) =>
        normalizedId.startsWith(pkgInfo.basePath),
      );

      if (!match) return;

      const [, pkgInfo] = match;

      const transformedCode = code.replace(
        /from\s+['"]((?:\.\.?)\/?[^'"]*)['"]/g,
        (full, relImport) => {
          const absImportPath = path.resolve(
            path.dirname(normalizedId),
            relImport,
          );
          const relativePath = path
            .relative(pkgInfo.basePath, absImportPath)
            .replace(/\\/g, '/');
          return `from '${pkgInfo.name}/${relativePath}'`;
        },
      );

      return {
        code: transformedCode,
        map: null,
      };
    },
  };
}

export const PloneRegistryVitePlugin = () => {
  const projectRootPath = path.resolve('.');
  const { registry, shadowAliases } = AddonRegistry.init(projectRootPath);

  const ploneDir = path.join(projectRootPath, '.plone');
  if (!fs.existsSync(ploneDir)) {
    fs.mkdirSync(ploneDir, { recursive: true });
  }

  const addonsLoaderPath = createAddonsLoader(
    registry.getAddonDependencies(),
    registry.getAddons(),
    { tempInProject: true },
  );
  createAddonsServerLoader(
    registry.getAddonDependencies(),
    registry.getAddons(),
  );
  createViteLoader(getAddonViteExtenders(registry));
  createAddonsStyleLoader(registry);
  createAddonsLocalesLoader(registry);

  const [addonsThemeLoaderVariablesPath, addonsThemeLoaderMainPath] =
    createThemeAddonsLoader(registry.getCustomThemeAddons());

  const addOns = Object.keys(registry.packages);

  const addonAliases = Object.values(registry.packages).map((pkg) => ({
    find: pkg.name,
    replacement: path.resolve(pkg.basePath),
  }));

  return [
    relativeToAbsoluteImportPlugin({
      packages: registry.packages,
    }),
    {
      name: 'plone-registry',
      enforce: 'pre',
      config: () => ({
        ssr: {
          optimizeDeps: {
            exclude: addOns,
          },
        },
        esbuild: {
          supported: {
            'top-level-await': true, //browsers can handle top-level-await features
          },
        },
        optimizeDeps: {
          exclude: addOns,
        },
        resolve: {
          alias: [
            ...shadowAliases,
            // This is still needed for internal resolution to "self"
            // in combination with shadowing
            ...addonAliases,
            // ToDo: Deprecate `theme` feature in Seven
            ...(registry.theme
              ? // Load the theme aliases from the theme config
                [
                  {
                    find: 'addonsThemeCustomizationsVariables',
                    replacement: addonsThemeLoaderVariablesPath,
                  },
                  {
                    find: 'addonsThemeCustomizationsMain',
                    replacement: addonsThemeLoaderMainPath,
                  },
                ]
              : []),
            // This is no longer needed in Seven
            {
              find: '@plone/registry/addons-loader',
              replacement: addonsLoaderPath,
            },
          ],
        },
      }),
    },
  ];
};
