version: "3"

services:

  addon-dev:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.acceptance
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
      HOST: 0.0.0.0
    ports:
      - 3000:3000
      - 3001:3001
    tty: true
    depends_on:
      - backend-acceptance
    profiles:
      - dev

  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    image: plone/server-acceptance:${PLONE_VERSION:-6}
    ports:
      - 55001:55001
    profiles:
      - dev
      - prod
