# .github/workflows/docs-rtd-pr-preview-volto.yml
name: readthedocs/storybook/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files for Volto.
    branches:
      - seven
    paths:
      - "packages/components/.storybook/**"
      - "packages/components/**/*.stories.*"
      - "packages/registry/.storybook/**"
      - "packages/registry/**/*.stories.*"
      - "packages/layout/.storybook/**"
      - "packages/layout/**/*.stories.*"
      - "packages/cmsui/.storybook/**"
      - "packages/cmsui/**/*.stories.*"
      - "packages/components/.readthedocs.yaml"

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            components:
              - 'packages/components/**/*.stories.*'

      - name: plone/components changelog check
        if: steps.filter.outputs.components == 'true'
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: "plone-components"
          single-version: "true"
