name: Translations Coverage DE
on: [push]
jobs:
  i18n-coverage:
    runs-on: ubuntu-latest
    name: Check i18n coverage
    steps:
      - uses: actions/checkout@v2
      - name: Check i18n coverage
        uses: alexkiro/i18n-coverage@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          translations-path: 'locales/de/LC_MESSAGES/*.po'
          only-languages: 'de'
          min-coverage: 100
      - name: Get the coverage
        run: echo "The coverage was ${{ steps.i18nCoverage.outputs.coverage }}"